{
  "_args": [
    [
      "chai-catch-exception",
      "/Users/jrobert/learning"
    ]
  ],
  "_from": "chai-catch-exception@*",
  "_id": "chai-catch-exception@1.0.0",
  "_inCache": true,
  "_location": "/chai-catch-exception",
  "_npmUser": {
    "email": "rgoyard@gmail.com",
    "name": "rgoyard"
  },
  "_npmVersion": "1.4.4",
  "_phantomChildren": {},
  "_requested": {
    "name": "chai-catch-exception",
    "raw": "chai-catch-exception",
    "rawSpec": "",
    "scope": null,
    "spec": "*",
    "type": "range"
  },
  "_requiredBy": [
    "#USER"
  ],
  "_resolved": "https://registry.npmjs.org/chai-catch-exception/-/chai-catch-exception-1.0.0.tgz",
  "_shasum": "08a5e9454e1a49fe4b8dadaeefc11014c6b57ff4",
  "_shrinkwrap": null,
  "_spec": "chai-catch-exception",
  "_where": "/Users/jrobert/learning",
  "author": "",
  "bugs": {
    "url": "https://github.com/mimiz/chai-catch-exception/issues"
  },
  "dependencies": {
    "chai": "~1.2.0"
  },
  "description": "A ChaiJs plugin inspired of catch-exception for Java ",
  "devDependencies": {
    "chai": "~1.6.1",
    "grunt": "~0.4.2",
    "grunt-bump": "0.0.13",
    "grunt-cli": "~0.1",
    "grunt-continue": "0.0.1",
    "grunt-contrib-jshint": "0.6.3",
    "grunt-mocha": "~0.4.1",
    "grunt-mocha-test": "~0.7.0",
    "jshint-path-reporter": "~0.1",
    "mocha": "~1.11.0",
    "mocha-unfunk-reporter": "~0.3.7",
    "requirejs": "~2.1.9"
  },
  "directories": {},
  "dist": {
    "shasum": "08a5e9454e1a49fe4b8dadaeefc11014c6b57ff4",
    "tarball": "http://registry.npmjs.org/chai-catch-exception/-/chai-catch-exception-1.0.0.tgz"
  },
  "homepage": "https://github.com/mimiz/chai-catch-exception",
  "installable": true,
  "keywords": [
    "chai",
    "mocha",
    "testing"
  ],
  "license": "MIT",
  "main": "chai-catch-exception.js",
  "maintainers": [
    {
      "name": "rgoyard",
      "email": "rgoyard@gmail.com"
    }
  ],
  "name": "chai-catch-exception",
  "optionalDependencies": {},
  "repository": {
    "type": "git",
    "url": "https://github.com/mimiz/chai-catch-exception.git"
  },
  "scripts": {
    "test": "grunt test"
  },
  "version": "1.0.0"
}
